# Generated by Django 3.1.1 on 2020-10-13 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_user_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
