# Generated by Django 3.1.1 on 2020-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201013_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
