# Generated by Django 3.1.1 on 2020-10-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20201014_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='temparory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('choice1', models.CharField(max_length=200)),
                ('choice2', models.CharField(max_length=200)),
                ('choice3', models.CharField(max_length=200)),
                ('choice4', models.CharField(max_length=200)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
    ]
